# Generated by Django 4.2.4 on 2024-05-20 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_search'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Search',
        ),
    ]
