# Generated by Django 4.2.4 on 2024-05-20 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_comment_parent_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent_comment',
        ),
    ]
